### ISSUE TITLE
How to make the slider slide right to the end?

### ISSUE THREAD

**Issue by philip-keep** [Stryzhevskyi/rangeSlider#52]
Hello,
Thanks for your range slider.
Aim: restyle the slider that the line is a lot thinner and the handle smaller. 

I can do this in the css but then the handle wont then reach the end of the slider, it stops before the end. I can't see a way to make it reach the end using css. Is it possible to resize the handle and line and still have it reach the very end of the line? Thanks.

**Comment by kevinwong150** [comment]
I believe this is the situation you mentioned, the handle just won't reach the end:
![image](https://user-images.githubusercontent.com/13821768/74811465-797b1f80-532c-11ea-885a-342bddcff382.png)
![image](https://user-images.githubusercontent.com/13821768/74811500-88fa6880-532c-11ea-8565-194f0503045a.png)

since the width of the handle somehow cause the issue, my workaround is to set the `max-width: 0;` to the handle, and skin the handle UI with its pseudo element(::before/::after):
![image](https://user-images.githubusercontent.com/13821768/74811677-f3130d80-532c-11ea-9d99-16e19c188364.png)
![image](https://user-images.githubusercontent.com/13821768/74811693-ff976600-532c-11ea-8336-5c02db4dc511.png)

**Comment by philip-keep** [comment]
Ah, thanks for sharing Kevin, appreciated.
